"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var circom = require('circom');
var circomlib_1 = require("circomlib");
var maci_crypto_1 = require("maci-crypto");
var F = circomlib_1.babyJub.F;
var priv_key = (0, maci_crypto_1.genPrivKey)();
var pub_key = (0, maci_crypto_1.genPubKey)(priv_key);
var output_value = pub_key[0] + "," + pub_key[1] + "|" + priv_key;
console.log(output_value);
