dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  development:
    verifier: False
  Sepolia:
    verifier: True